trigger:
- master

variables:
  packer_version: 1.4.5

stages:
- stage: 'BuildPacker'
  displayName: 'Build Packer image'
  jobs: 
  - job: 'Packer'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: Azure
    steps:
    - script: |
        wget https://releases.hashicorp.com/packer/$(packer_version)/packer_$(packer_version)_linux_amd64.zip -O packer.zip
        unzip packer.zip
        ./packer build \
          -force \
          -var 'client_id=$(client_id)' \
          -var 'client_secret=$(client_secret)' \
          -var 'tenant_id=$(tenant_id)' \
          -var 'subscription_id=$(subscription_id)' \
          windows.json
      displayName: "Run Packer"
      env:
        client_id: $(client_id)
        client_secret: $(client_secret)
        tenant_id: $(tenant_id)
        subscription_id: $(subscription_id)