trigger:
- master

# Uncomment this to run the pipeline on a schedule.
# schedules:
# - cron: '0 3 * * 0'
#   displayName: Deploy every Sunday at 3 A.M. UTC
#   branches:
#     include:
#     - master
#   always: true

variables:
  packer_version: 1.4.5

stages:
- stage: 'BuildVmImage'
  displayName: 'Build Azure VM image'
  jobs: 
  - job: 'Packer'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: Azure
    steps:
    - script: |
        wget https://releases.hashicorp.com/packer/$(packer_version)/packer_$(packer_version)_linux_amd64.zip -O packer.zip
        unzip packer.zip
        ./packer build \
          -force \
          -var 'client_id=$(client_id)' \
          -var 'client_secret=$(client_secret)' \
          -var 'tenant_id=$(tenant_id)' \
          -var 'subscription_id=$(subscription_id)' \
          -var "managed_image_resource_group_name=$(managed_image_resource_group_name)" \
          -var "managed_image_name=$(managed_image_name)" \
          windows.json
      displayName: "Run Packer"
    - task: AzureCLI@2
      displayName: Publish to image gallery
      inputs:
        azureSubscription: Azure
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          GAL_NAME=$(GAL_NAME)
          AZ_LOCATION=$(AZ_LOCATION)
          TARGET_REGIONS=$(TARGET_REGIONS)
          IMG_URN=$(IMG_URN)

          az group create --name $GAL_NAME-rg --location $AZ_LOCATION

          az sig create \
            --resource-group $GAL_NAME-rg \
            --gallery-name $GAL_NAME \
            --location $AZ_LOCATION

          az sig image-definition create \
            --resource-group $GAL_NAME-rg \
            --gallery-name $GAL_NAME \
            --gallery-image-definition $GAL_NAME-imgdef \
            --publisher MicrosoftLearn \
            --offer WindowsServer \
            --sku 2019-Datacenter-Az-Pwsh \
            --os-type Windows \
            --location $AZ_LOCATION

          az sig image-version create \
            --resource-group $GAL_NAME-rg \
            --location $AZ_LOCATION \
            --gallery-name $GAL_NAME \
            --gallery-image-definition $GAL_NAME-imgdef \
            --gallery-image-version 1.0.0 \
            --target-regions $TARGET_REGIONS \
            --replica-count 2 \
            --managed-image $IMG_URN